<center><h1 style="color:#D4AF37"> ‚ö°‚ö° AEMR Data Analysis ‚ö°‚ö°</h1>

<img src = "https://images.squarespace-cdn.com/content/v1/551972d8e4b0d571edc2e2c8/8f3abd33-0916-4415-9b24-593eea1d1e3c/Screen+Shot+2022-04-20+at+12.41.24+PM.png">

  
It‚Äôs time for you to apply your budding SQL Competencies to analyse data for the American Energy Market Regulator (AEMR).

The analytics team has supplied you with the following table extract that contains all the data you need to analyse for the `AEMR` outages. 

<li> AEMR_Outage_Table </li> 
    
Now let's revisit the business problem below and understand what we're seeking to solve.

<h1 style="color:#D4AF37"> What's the Business Problem? üí∞</h1>

The American Energy Market Regulator (AEMR) is responsible for looking after the
United States of America‚Äôs domestic energy network. The regulator‚Äôs responsibility is to
ensure that America‚Äôs energy network remains reliable with minimal disruptions, which
are known as outages. 

There are four key types of outages:

‚óè Consequential

‚óè Forced 

‚óè Opportunistic 

‚óè Planned 

Recently, the AEMR management team has been increasingly aware of a large number
of energy providers that submitted outages over the 2016 and 2017 calendar years. The
management team has expressed a desire to have the following two areas of concern
addressed:

<b> A) Energy Stability and Market Outages
    <p>
B) Energy Losses and Market Reliability </b>

As an analyst within the data and reporting team, you have been asked to address these
two immediate areas of concern. Feel free to also explore beyond the queries asked and provide additional insights that you feel may be of interest to the management team.

<h3 style="color:#D4AF37">  SQLite Refresher ‚öôÔ∏è </h3>

We've pre-loaded the data you need to access in the `AEMR.db` we've included. We'll have you write SQL below where all your SQL queries will be stored in this notebook as a reference you can use when you review your data analysis in Tableau. </b>.

To load the `AEMR.db` file into this notebook, run the below cells.

<b> ‚ö†Ô∏è Please remember that everytime you close this file and re-open this, you'll need to re-run the cells below. ‚ö†Ô∏è </b>

<b>‚ö†Ô∏è Note: Remember, you'll need to start each cell with the **`%%sql`** line, which allows us to execute SQL from within this notebook.</b>

In [1]:
%%capture
!pip install ipython-sql sqlalchemy
import sqlalchemy
sqlalchemy.create_engine("sqlite:///AEMR.db")
%load_ext sql
%sql sqlite:///AEMR.db

In [2]:
%%js
require(['notebook/js/codecell'], function (codecell) {
    codecell.CodeCell.options_default.highlight_modes['magic_text/x-mssql'] = { 'reg': [/%?%sql/] };
    Jupyter.notebook.events.one('kernel_ready.Kernel', function () {
        Jupyter.notebook.get_cells().map(function (cell) {
            if (cell.cell_type == 'code') { cell.auto_highlight(); }
        });
    });
});

We've included an example of how you would write a query against the database below:

~~~sql
%%sql
SELECT
*
FROM AEMR_Outage_Table
LIMIT 10
~~~

Once you've written your SQL, you'll then need to press `Ctrl` + `Enter` to run the cell.
Otherwise, you can just press `run` at the very top of your screen, to run the specific cell.

For your convenience, we've included a <b style = "color:#5D3FD3"> subset of the answers </b> under the header `Expected Output (Sample)`. These small subsets also include all the `columns` you'll need to include in your Query, so you know what to expect!

Good luck!

<b>PS: In case any of you get stuck regarding how to tackle any of the questions, we've included a breakdown <a href = "https://drive.google.com/file/d/1sXBGV5MZooZ7L38WYyXf9lIaA5sdKL7X/view?usp=share_link"> here</a> where Chris walks through how to tackle each question! Feel free to use this when you're stuck and you can't book a Mentor Call! </b>

<h3 style="color:#D4AF37"> ‚ö° Part I. Energy Stability & Market Outages ‚ö° </h3>

Energy stability is one of the key themes the AEMR management team cares about. To ensure energy security and reliability, AEMR needs to understand the following:
<p>
<b>

<li> What are the most common outage types and how long do they tend to last? 
<li> How frequently do the outages occur? 
<li> Are there any energy providers which have more outages than their peers which may be indicative of being unreliable? 
    
<p>

<u style="color:Maroon"> Please note that throughout the entire case study, we are interested ONLY in the Outages where Status = Approved. We don't have any interest in Outages that were cancelled or not approved. This means your WHERE Clause will ALWAYS contain the field `Where Status = Approved` </u>

<h3 style="color:#D4AF37"> Question One </h3> 

<b> Write a SQL Statement to `COUNT` the number of valid (i.e. `Status = Approved`) Outage Events sorted by their respective `Outage_Reason` (i.e. `Forced`, `Consequential`, `Scheduled`, `Opportunistic`) over the 2016 & 2017 Periods. </b>

Do we notice anything regarding the trends for specific Outages over the 2016 / 2017 Period?

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

<b>‚ö†Ô∏è Note: Remember, you'll need to start each cell with the **`%%sql`** line, which allows us to execute SQL from within this notebook.</b>

In [3]:
%%sql


select count(*) as Total_Number_Outages, Outage_reason, year
from AEMR_Outage_Table
where status = 'Approved'
Group by Outage_reason, Year
Limit 10

 * sqlite:///AEMR.db
Done.

[(181, 'Consequential', 2016),
 (127, 'Consequential', 2017),
 (1264, 'Forced', 2016),
 (1622, 'Forced', 2017),
 (106, 'Opportunistic Maintenance (Planned)', 2016),
 (102, 'Opportunistic Maintenance (Planned)', 2017),
 (380, 'Scheduled (Planned)', 2016),
 (320, 'Scheduled (Planned)', 2017)]

In [ ]:
%% sql 
select

In [112]:
%%sql
SELECT
*
FROM AEMR_Outage_Table
LIMIT 10

 * sqlite:///AEMR.db
Done.

[(1, '2017-12-28 06:00', '2017-12-28 10:00', 2017, 12, 'DNHR_DENMARK_WF1', 'DNHR', 'Approved', 'Consequential', 1.44, 'a network outage in Denmark caused the windfarm to trip at 6:26 am'),
 (2, '2017-12-26 09:00', '2017-12-27 00:00', 2017, 12, 'COLLGAR_WF1', 'COLLGAR', 'Approved', 'Forced', 30.0, 'Forced Outage - BS on Overhead line pole S-81 - CG10/11'),
 (3, '2017-12-31 09:00', '2017-12-31 09:00', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 5.702999999999999, 'Under generation - ambient conditions'),
 (4, '2017-12-31 08:30', '2017-12-31 08:30', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 5.085, 'Under generation - ambient conditions'),
 (5, '2017-12-31 08:00', '2017-12-31 08:00', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 5.02, 'Under generation - ambient conditions'),
 (6, '2017-12-30 23:30', '2017-12-30 23:30', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 5.79, 'Under generation - ambient conditions'),
 (7, '2017-12-30 23:00', '2017-12-30 23:00', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 5.412000000000001, 'Under generation - ambient conditions'),
 (8, '2017-12-30 22:30', '2017-12-30 22:30', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 4.735, 'Under generation - ambient conditions'),
 (9, '2017-12-29 23:30', '2017-12-29 23:30', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 4.245, 'Under generation - ambient conditions'),
 (10, '2017-12-29 23:00', '2017-12-29 23:00', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 3.9619999999999997, 'Under generation - ambient conditions')]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

 * sqlite:///AEMR.db
Done.

[(181, 'Consequential', 2016),
 (1264, 'Forced', 2016),
 (106, 'Opportunistic Maintenance (Planned)', 2016),
 (380, 'Scheduled (Planned)', 2016)]

Now how about examining some monthly trends? Do we note any behaviours across the months that indicate certain months having more reliability issues over other months?

<h3 style="color:#D4AF37"> Question Two </h3>

<b> i) Write a SQL Statement showing the `Total` of all Outage Types (Forced, Consequential, Scheduled, Opportunistic) where the `Status = Approved`, that occurred for both 2016 and 2017, grouped by `Year` and `Month`.  per month (i.e. 1 ‚Äì 12). Order by `Year`, `Month`, `Total_Number_Outages` in Descending Order.


ii) Building on the query you write in i), group the results by `Outage Type`, `Year` and `Month`. This is so you can identify whether there is any outage type specifically increasing on a monthly basis when comparing 2016 to 2017. </b>


<b>‚ö†Ô∏èHint: You might find it helpful to create a small Common Table Expression to address these two questions! </b>

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [65]:
%%sql
select
Count(*) as Total_Number_Outages, Year, Month
from AEMR_Outage_Table 
Where Status = 'Approved'
Group by Year, Month
Limit 10

 * sqlite:///AEMR.db
Done.

[(191, 2016, 1),
 (227, 2016, 2),
 (136, 2016, 3),
 (134, 2016, 4),
 (174, 2016, 5),
 (168, 2016, 6),
 (147, 2016, 7),
 (194, 2016, 8),
 (124, 2016, 9),
 (124, 2016, 10)]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

 * sqlite:///AEMR.db
Done.

[(2016, 1, 191),
 (2016, 2, 227),
 (2016, 3, 136),
 (2016, 4, 134),
 (2016, 5, 174)]

Hmm. Interesting. We've now identified a specific outage type is rapidly increasing from 2016 to 2017. However, frequency is just one aspect we care about. We also care about the <b> `duration` </b> of our ouatges.

In other words, if an outage is very short, we aren't as concerned. However, if the outage is very long, this then has the risk of threatening our energy supplies. We want to identify the problematic energy providers here. This leads us to our next question below.

<h3 style="color:#D4AF37"> Question Three </h3>

<b>Write a SQL statement that calculates 1) The `Total_Number_Outage_Events` and 2) The <b> `Average Duration`</b> in <u>DAYS</u> for each `Participant Code` and `Outage Type` over the 2016 and 2017 Period where the `Status = Approved`. 
Order by `Total_Number_Outage_Events` in Descending Order, `Reason` and `Year`.
    
Please note the average duration in days should be rounded to 2 decimal places for ease of comparison. When calculating the average duration, please note that you'll need to use the following fields:

`Start_Time` and `End_Time`. </b>

<b>‚ö†Ô∏è Hint:</b> If you're not sure how to calculate the difference between the `start_time` and `end_time` , reference this link <a href ="https://learnsql.com/cookbook/how-to-calculate-the-difference-between-two-timestamps-in-sqlite/"> here </a>

We've included an example below of how you could use the `JULIANDAY()` function! Remember, the `JULIANDAY()` function returns the results in days, including the fractional component. Some of the date(s) are flipped in the dataset, so you'll need to use the ABS() function to ensure you don't return any negative values!

~~~sql
%%sql

SELECT
        AVG((ABS(JULIANDAY(Date_2) - JULIANDAY(Date1))) 
FROM Some_Database
~~~

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [68]:
%%sql
select 
Count(*) as total_number_outage_events,year, Participant_code, year,
round(avg(abs(Julianday(End_Time) - Julianday(Start_time))),2) as Average_Outage_Duration_In_Days
from AEMR_Outage_Table
where status = 'Approved'
group by Participant_code, Outage_Reason, year
Order by Total_Number_Outage_Events Desc
Limit 10

 * sqlite:///AEMR.db
Done.

[(490, 2017, 'AURICON', 2017, 0.07),
 (317, 2016, 'GW', 2016, 0.38),
 (227, 2017, 'GW', 2017, 1.06),
 (208, 2016, 'AURICON', 2016, 0.07),
 (206, 2016, 'AUXC', 2016, 0.08),
 (177, 2017, 'MELK', 2017, 2.28),
 (172, 2017, 'TRMOS', 2017, 0.42),
 (157, 2016, 'MELK', 2016, 0.83),
 (135, 2017, 'PUG', 2017, 0.25),
 (120, 2017, 'AUXC', 2017, 0.02)]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

Now we're getting somewhere...!
We've identified participants who are having many outages, as well as participants who have been offline for the longest durations.

Armed with this information, it's important we're able to classify our participants accordingly based on reliability metrics of uptime.

We classify a participant based off the following criteria:
<b>
<li> High Risk - On average, the participant is unavailable for > 24 Hours (1 Day)</li>
<li> Medium Risk - On average, the participant is unavailable between 12 and 24 Hours </li>
<li> Low Risk - On average, the participant is unavailable for less than 12 Hours</li> 
</b>

<h3 style="color:#D4AF37"> Question Four </h3>

<b> Using the above criteria for context, write a SQL Statement that <u> classifies each participant code as either `High Risk`, `Medium Risk` or `Low Risk` in a column called `Risk_Classification`</u> that is based off their Average Outage Duration Time. Please note that this is for all valid (i.e. `Where status = approved`) outage types (Forced, Consequential, Scheduled, Opportunistic) for <u>all</u> participant codes from 2016 to 2017. Order the results using `Average Duration Time In Days` in descending order. 

<b>‚ö†Ô∏èHint: Think about the CASE Statement and how you might use this to help you with your classification! This is a more challenging question so you'll need to think through this step by step. You might also find `CTEs` or `Sub Queries` helpful for you.</b>

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [78]:
%%sql
with CTE1 as (
    select 
Count(*) as total_number_outage_events,year, Participant_code, year,
round(avg(abs(Julianday(End_Time) - Julianday(Start_time))),2) as Average_Outage_Duration_In_Days
from AEMR_Outage_Table
where status = 'Approved'
group by Participant_code, Outage_Reason, year
Order by Total_Number_Outage_Events Desc
)
Select *,
CASE 
 when Average_Outage_Duration_In_Days > 1 Then 'High Risk'
  when Average_Outage_Duration_In_Days Between 0.5 and 1 Then 'Medium Risk'
   when Average_Outage_Duration_In_Days Between 0 and 0.5 Then 'Low risk'
   Else 'N/A'
   END as Risk_Classification
   from CTE1;

 * sqlite:///AEMR.db
Done.

[(490, 2017, 'AURICON', 2017, 0.07, 'Low risk'),
 (317, 2016, 'GW', 2016, 0.38, 'Low risk'),
 (227, 2017, 'GW', 2017, 1.06, 'High Risk'),
 (208, 2016, 'AURICON', 2016, 0.07, 'Low risk'),
 (206, 2016, 'AUXC', 2016, 0.08, 'Low risk'),
 (177, 2017, 'MELK', 2017, 2.28, 'High Risk'),
 (172, 2017, 'TRMOS', 2017, 0.42, 'Low risk'),
 (157, 2016, 'MELK', 2016, 0.83, 'Medium Risk'),
 (135, 2017, 'PUG', 2017, 0.25, 'Low risk'),
 (120, 2017, 'AUXC', 2017, 0.02, 'Low risk'),
 (85, 2016, 'MELK', 2016, 4.61, 'High Risk'),
 (81, 2016, 'PJRH', 2016, 1.22, 'High Risk'),
 (76, 2017, 'KORL', 2017, 1.21, 'High Risk'),
 (72, 2017, 'PJRH', 2017, 0.84, 'Medium Risk'),
 (70, 2017, 'MELK', 2017, 6.89, 'High Risk'),
 (69, 2016, 'PMC', 2016, 0.49, 'Low risk'),
 (65, 2016, 'TRMOS', 2016, 0.19, 'Low risk'),
 (53, 2016, 'KORL', 2016, 0.38, 'Low risk'),
 (46, 2016, 'AURICON', 2016, 1.89, 'High Risk'),
 (45, 2017, 'AURICON', 2017, 1.45, 'High Risk'),
 (45, 2017, 'COLLGAR', 2017, 1.38, 'High Risk'),
 (45, 2016, 'GW', 2016, 4.43, 'High Risk'),
 (42, 2017, 'AURICON', 2017, 0.21, 'Low risk'),
 (41, 2016, 'AURICON', 2016, 0.13, 'Low risk'),
 (40, 2017, 'PMC', 2017, 0.04, 'Low risk'),
 (39, 2017, 'PJRH', 2017, 0.24, 'Low risk'),
 (38, 2016, 'PJRH', 2016, 2.37, 'High Risk'),
 (37, 2017, 'ENRG', 2017, 4.96, 'High Risk'),
 (35, 2017, 'PJRH', 2017, 2.61, 'High Risk'),
 (30, 2016, 'TSLA_MGT', 2016, 0.44, 'Low risk'),
 (29, 2016, 'COLLGAR', 2016, 1.11, 'High Risk'),
 (29, 2016, 'ENRG', 2016, 4.85, 'High Risk'),
 (28, 2017, 'TSLA_MGT', 2017, 0.99, 'Medium Risk'),
 (27, 2016, 'PMC', 2016, 1.9, 'High Risk'),
 (26, 2017, 'GW', 2017, 2.65, 'High Risk'),
 (24, 2016, 'MELK', 2016, 0.71, 'Medium Risk'),
 (24, 2016, 'PUG', 2016, 0.92, 'Medium Risk'),
 (23, 2016, 'PJRH', 2016, 0.18, 'Low risk'),
 (23, 2017, 'TSLA_MGT', 2017, 0.34, 'Low risk'),
 (23, 2016, 'TSLA_MGT', 2016, 1.97, 'High Risk'),
 (21, 2016, 'ENRG', 2016, 2.24, 'High Risk'),
 (20, 2016, 'GW', 2016, 0.18, 'Low risk'),
 (20, 2016, 'GW', 2016, 0.31, 'Low risk'),
 (20, 2016, 'KORL', 2016, 6.96, 'High Risk'),
 (18, 2016, 'MUND', 2016, 3.53, 'High Risk'),
 (18, 2017, 'STHRNCRS', 2017, 0.26, 'Low risk'),
 (17, 2016, 'EUCT', 2016, 0.41, 'Low risk'),
 (16, 2017, 'KORL', 2017, 3.38, 'High Risk'),
 (16, 2017, 'MELK', 2017, 0.65, 'Medium Risk'),
 (16, 2016, 'PUG', 2016, 1.47, 'High Risk'),
 (15, 2016, 'ENRG', 2016, 0.57, 'Medium Risk'),
 (15, 2017, 'MUND', 2017, 0.19, 'Low risk'),
 (14, 2017, 'EUCT', 2017, 0.32, 'Low risk'),
 (14, 2016, 'KORL', 2016, 0.22, 'Low risk'),
 (14, 2017, 'STHRNCRS', 2017, 0.68, 'Medium Risk'),
 (13, 2017, 'GW', 2017, 0.28, 'Low risk'),
 (13, 2016, 'STHRNCRS', 2016, 0.33, 'Low risk'),
 (13, 2016, 'STHRNCRS', 2016, 0.62, 'Medium Risk'),
 (12, 2016, 'COLLGAR', 2016, 0.6, 'Medium Risk'),
 (12, 2016, 'COLLGAR', 2016, 4.28, 'High Risk'),
 (12, 2017, 'DNHR', 2017, 0.24, 'Low risk'),
 (12, 2017, 'MCG', 2017, 0.28, 'Low risk'),
 (12, 2017, 'PMC', 2017, 1.7, 'High Risk'),
 (11, 2016, 'DNHR', 2016, 0.28, 'Low risk'),
 (11, 2016, 'EUCT', 2016, 5.9, 'High Risk'),
 (11, 2017, 'PUG', 2017, 2.25, 'High Risk'),
 (10, 2017, 'KORL', 2017, 0.24, 'Low risk'),
 (10, 2016, 'PMC', 2016, 0.28, 'Low risk'),
 (9, 2017, 'COLLGAR', 2017, 6.36, 'High Risk'),
 (9, 2017, 'MUND', 2017, 0.21, 'Low risk'),
 (9, 2016, 'STHRNCRS', 2016, 0.22, 'Low risk'),
 (8, 2016, 'MUND', 2016, 0.15, 'Low risk'),
 (8, 2017, 'PMC', 2017, 3.52, 'High Risk'),
 (8, 2017, 'WGUTD', 2017, 3.44, 'High Risk'),
 (7, 2017, 'ENRG', 2017, 0.27, 'Low risk'),
 (7, 2017, 'ENRG', 2017, 0.26, 'Low risk'),
 (7, 2016, 'MELK', 2016, 0.76, 'Medium Risk'),
 (7, 2017, 'MUND', 2017, 1.7, 'High Risk'),
 (7, 2016, 'PUG', 2016, 0.21, 'Low risk'),
 (6, 2017, 'KORL', 2017, 2.24, 'High Risk'),
 (6, 2016, 'WGUTD', 2016, 1.99, 'High Risk'),
 (5, 2017, 'COLLGAR', 2017, 0.23, 'Low risk'),
 (5, 2017, 'COLLGAR', 2017, 0.33, 'Low risk'),
 (5, 2016, 'TRMOS', 2016, 1.42, 'High Risk'),
 (4, 2016, 'ENRG', 2016, 0.47, 'Low risk'),
 (4, 2017, 'GW', 2017, 0.24, 'Low risk'),
 (4, 2017, 'MCG', 2017, 0.06, 'Low risk'),
 (4, 2016, 'MUND', 2016, 0.37, 'Low risk'),
 (4, 2017, 'TRMOS', 2017, 2.31, 'High Risk'),
 (4, 2017, 'TSLA_MGT', 2017, 0.31, 'Low risk'),
 (3, 2016, 'AURICON', 2016, 0.33, 'Low risk'),
 (3, 2017, 'ENRG', 2017, 0.35, 'Low risk'),
 (3, 2017, 'EUCT', 2017, 0.03, 'Low risk'),
 (3, 2017, 'PUG', 2017, 0.24, 'Low risk'),
 (2, 2016, 'AUXC', 2016, 1.25, 'High Risk'),
 (2, 2016, 'MCG', 2016, 0.26, 'Low risk'),
 (2, 2017, 'MCG', 2017, 0.23, 'Low risk'),
 (2, 2017, 'STHRNCRS', 2017, 0.26, 'Low risk'),
 (2, 2016, 'TSLA_MGT', 2016, 0.25, 'Low risk'),
 (2, 2016, 'WGUTD', 2016, 0.02, 'Low risk'),
 (2, 2017, 'WGUTD', 2017, 0.05, 'Low risk'),
 (1, 2016, 'AUXC', 2016, 0.96, 'Medium Risk'),
 (1, 2017, 'AUXC', 2017, 0.1, 'Low risk'),
 (1, 2017, 'AUXC', 2017, 2.88, 'High Risk'),
 (1, 2016, 'DNHR', 2016, 0.4, 'Low risk'),
 (1, 2017, 'DNHR', 2017, 0.48, 'Low risk'),
 (1, 2016, 'MCG', 2016, 0.79, 'Medium Risk'),
 (1, 2016, 'MCG', 2016, 1.42, 'High Risk'),
 (1, 2016, 'PMC', 2016, 0.08, 'Low risk'),
 (1, 2017, 'PMC', 2017, 0.25, 'Low risk'),
 (1, 2017, 'STHRNCRS', 2017, 0.06, 'Low risk'),
 (1, 2016, 'TRMOS', 2016, 0.06, 'Low risk'),
 (1, 2017, 'WGUTD', 2017, 0.04, 'Low risk'),
 (1, 2016, 'WGUTD', 2016, 0.6, 'Medium Risk'),
 (1, 2017, 'WGUTD', 2017, 10.58, 'High Risk')]

In [59]:
%%sql
SELECT
*
FROM AEMR_Outage_Table
LIMIT 10

 * sqlite:///AEMR.db
Done.

[(1, '2017-12-28 06:00', '2017-12-28 10:00', 2017, 12, 'DNHR_DENMARK_WF1', 'DNHR', 'Approved', 'Consequential', 1.44, 'a network outage in Denmark caused the windfarm to trip at 6:26 am'),
 (2, '2017-12-26 09:00', '2017-12-27 00:00', 2017, 12, 'COLLGAR_WF1', 'COLLGAR', 'Approved', 'Forced', 30.0, 'Forced Outage - BS on Overhead line pole S-81 - CG10/11'),
 (3, '2017-12-31 09:00', '2017-12-31 09:00', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 5.702999999999999, 'Under generation - ambient conditions'),
 (4, '2017-12-31 08:30', '2017-12-31 08:30', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 5.085, 'Under generation - ambient conditions'),
 (5, '2017-12-31 08:00', '2017-12-31 08:00', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 5.02, 'Under generation - ambient conditions'),
 (6, '2017-12-30 23:30', '2017-12-30 23:30', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 5.79, 'Under generation - ambient conditions'),
 (7, '2017-12-30 23:00', '2017-12-30 23:00', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 5.412000000000001, 'Under generation - ambient conditions'),
 (8, '2017-12-30 22:30', '2017-12-30 22:30', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 4.735, 'Under generation - ambient conditions'),
 (9, '2017-12-29 23:30', '2017-12-29 23:30', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 4.245, 'Under generation - ambient conditions'),
 (10, '2017-12-29 23:00', '2017-12-29 23:00', 2017, 12, 'AURICON_PNJ_U1', 'AURICON', 'Approved', 'Forced', 3.9619999999999997, 'Under generation - ambient conditions')]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

 * sqlite:///AEMR.db
Done.

[('AURICON', 'Forced', 2017, 490, 0.07, 'Low Risk'),
 ('GW', 'Forced', 2016, 317, 0.38, 'Low Risk'),
 ('GW', 'Forced', 2017, 227, 1.06, 'High Risk')]

Now that we've classified our participants as either `High Risk`, `Medium Risk` or `Low Risk`, we want to dig a little deeper.

Does it make sense that `Consequential`, `Opportunistic` or `Planned` aren't considered regarding the Risk Category?

Perhaps we should refine our category accordingly by ensuring we focus our Risk Category on labelling only `Forced` Outages as being a Risk. After all, Forced Outages are the unplanned outages that risk the security of the electricity grid.

Let's add two additional criteria to our classification considering `Total Number of Outage Events` and `Outage Type`.

We've summarised these below:

<b>
<li> High Risk - On average, the participant is unavailable for > 24 Hours (1 Day) OR the Total Number of Outage Events > 20 </li>
<li> Medium Risk - On average, the participant is unavailable between 12 and 24 Hours OR the Total Number of Outage Events is Between 10 and 20 </li>
<li> Low Risk - On average, the participant is unavailable for less than 12 Hours OR the Total Number of Outage Events < 10 </li> 
<li> If Outage Type is not forced, then N/A
</b>

<h3 style="color:#D4AF37"> Question Five </h3>

<b> Just as you did in Question Four, Using the above criteria for context, write a SQL Statement that <u> classifies each participant code as either `High Risk`, `Medium Risk` or `Low Risk` in a column called `Risk_Classification`</u> using the new classification criteria. Order the results using `Average Duration Time In Days` in descending order. 

<b>‚ö†Ô∏èHint: Think about the CASE Statement and how you might use this to help you with your classification! </b>

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [83]:
%%sql
with CTE1 as (
    select 
    Participant_Code,
    Outage_reason, 
    Year,
    Count(*) as Total_Number_Outage_Events,
    Round(AVG(ABS(Julianday(End_Time) - Julianday(Start_Time))),2) as Average_Outage_Duration_In_Days
    From AEMR_Outage_Table
    where status = 'Approved'
    Group by Participant_code, Outage_Reason, year
    order by Total_Number_Outage_Events DESC    
) 
Select *,
CASE 
 when Average_Outage_Duration_In_Days > 1 and Outage_Reason = 'Forced' or Total_Number_Outage_Events > 20 and Outage_Reason = 'Forced' then 'High Risk'
  when Average_Outage_Duration_In_Days Between 0.5 and 1 and outage_reason = 'Forced' OR Total_Number_Outage_Events Between 10 and 20 and Outage_Reason = 'Forced' then 'Medium Risk' 
   when Average_Outage_Duration_In_Days Between 0 and 0.5 and outage_reason = 'Forced' OR Total_Number_Outage_Events < 10 and outage_reason =  'Forced' then 'Low risk'
   Else 'N/A'
   END as Risk_Classification
   from CTE1;

 * sqlite:///AEMR.db
Done.

[('AURICON', 'Forced', 2017, 490, 0.07, 'High Risk'),
 ('GW', 'Forced', 2016, 317, 0.38, 'High Risk'),
 ('GW', 'Forced', 2017, 227, 1.06, 'High Risk'),
 ('AURICON', 'Forced', 2016, 208, 0.07, 'High Risk'),
 ('AUXC', 'Forced', 2016, 206, 0.08, 'High Risk'),
 ('MELK', 'Forced', 2017, 177, 2.28, 'High Risk'),
 ('TRMOS', 'Forced', 2017, 172, 0.42, 'High Risk'),
 ('MELK', 'Forced', 2016, 157, 0.83, 'High Risk'),
 ('PUG', 'Forced', 2017, 135, 0.25, 'High Risk'),
 ('AUXC', 'Forced', 2017, 120, 0.02, 'High Risk'),
 ('MELK', 'Scheduled (Planned)', 2016, 85, 4.61, 'N/A'),
 ('PJRH', 'Forced', 2016, 81, 1.22, 'High Risk'),
 ('KORL', 'Forced', 2017, 76, 1.21, 'High Risk'),
 ('PJRH', 'Forced', 2017, 72, 0.84, 'High Risk'),
 ('MELK', 'Scheduled (Planned)', 2017, 70, 6.89, 'N/A'),
 ('PMC', 'Forced', 2016, 69, 0.49, 'High Risk'),
 ('TRMOS', 'Forced', 2016, 65, 0.19, 'High Risk'),
 ('KORL', 'Forced', 2016, 53, 0.38, 'High Risk'),
 ('AURICON', 'Scheduled (Planned)', 2016, 46, 1.89, 'N/A'),
 ('AURICON', 'Scheduled (Planned)', 2017, 45, 1.45, 'N/A'),
 ('COLLGAR', 'Forced', 2017, 45, 1.38, 'High Risk'),
 ('GW', 'Scheduled (Planned)', 2016, 45, 4.43, 'N/A'),
 ('AURICON', 'Consequential', 2017, 42, 0.21, 'N/A'),
 ('AURICON', 'Consequential', 2016, 41, 0.13, 'N/A'),
 ('PMC', 'Forced', 2017, 40, 0.04, 'High Risk'),
 ('PJRH', 'Opportunistic Maintenance (Planned)', 2017, 39, 0.24, 'N/A'),
 ('PJRH', 'Scheduled (Planned)', 2016, 38, 2.37, 'N/A'),
 ('ENRG', 'Scheduled (Planned)', 2017, 37, 4.96, 'N/A'),
 ('PJRH', 'Scheduled (Planned)', 2017, 35, 2.61, 'N/A'),
 ('TSLA_MGT', 'Consequential', 2016, 30, 0.44, 'N/A'),
 ('COLLGAR', 'Forced', 2016, 29, 1.11, 'High Risk'),
 ('ENRG', 'Scheduled (Planned)', 2016, 29, 4.85, 'N/A'),
 ('TSLA_MGT', 'Scheduled (Planned)', 2017, 28, 0.99, 'N/A'),
 ('PMC', 'Scheduled (Planned)', 2016, 27, 1.9, 'N/A'),
 ('GW', 'Scheduled (Planned)', 2017, 26, 2.65, 'N/A'),
 ('MELK', 'Opportunistic Maintenance (Planned)', 2016, 24, 0.71, 'N/A'),
 ('PUG', 'Forced', 2016, 24, 0.92, 'High Risk'),
 ('PJRH', 'Opportunistic Maintenance (Planned)', 2016, 23, 0.18, 'N/A'),
 ('TSLA_MGT', 'Consequential', 2017, 23, 0.34, 'N/A'),
 ('TSLA_MGT', 'Scheduled (Planned)', 2016, 23, 1.97, 'N/A'),
 ('ENRG', 'Forced', 2016, 21, 2.24, 'High Risk'),
 ('GW', 'Consequential', 2016, 20, 0.18, 'N/A'),
 ('GW', 'Opportunistic Maintenance (Planned)', 2016, 20, 0.31, 'N/A'),
 ('KORL', 'Scheduled (Planned)', 2016, 20, 6.96, 'N/A'),
 ('MUND', 'Scheduled (Planned)', 2016, 18, 3.53, 'N/A'),
 ('STHRNCRS', 'Forced', 2017, 18, 0.26, 'Medium Risk'),
 ('EUCT', 'Consequential', 2016, 17, 0.41, 'N/A'),
 ('KORL', 'Scheduled (Planned)', 2017, 16, 3.38, 'N/A'),
 ('MELK', 'Opportunistic Maintenance (Planned)', 2017, 16, 0.65, 'N/A'),
 ('PUG', 'Scheduled (Planned)', 2016, 16, 1.47, 'N/A'),
 ('ENRG', 'Consequential', 2016, 15, 0.57, 'N/A'),
 ('MUND', 'Forced', 2017, 15, 0.19, 'Medium Risk'),
 ('EUCT', 'Consequential', 2017, 14, 0.32, 'N/A'),
 ('KORL', 'Opportunistic Maintenance (Planned)', 2016, 14, 0.22, 'N/A'),
 ('STHRNCRS', 'Scheduled (Planned)', 2017, 14, 0.68, 'N/A'),
 ('GW', 'Opportunistic Maintenance (Planned)', 2017, 13, 0.28, 'N/A'),
 ('STHRNCRS', 'Forced', 2016, 13, 0.33, 'Medium Risk'),
 ('STHRNCRS', 'Scheduled (Planned)', 2016, 13, 0.62, 'N/A'),
 ('COLLGAR', 'Consequential', 2016, 12, 0.6, 'N/A'),
 ('COLLGAR', 'Scheduled (Planned)', 2016, 12, 4.28, 'N/A'),
 ('DNHR', 'Consequential', 2017, 12, 0.24, 'N/A'),
 ('MCG', 'Forced', 2017, 12, 0.28, 'Medium Risk'),
 ('PMC', 'Scheduled (Planned)', 2017, 12, 1.7, 'N/A'),
 ('DNHR', 'Consequential', 2016, 11, 0.28, 'N/A'),
 ('EUCT', 'Forced', 2016, 11, 5.9, 'High Risk'),
 ('PUG', 'Scheduled (Planned)', 2017, 11, 2.25, 'N/A'),
 ('KORL', 'Opportunistic Maintenance (Planned)', 2017, 10, 0.24, 'N/A'),
 ('PMC', 'Consequential', 2016, 10, 0.28, 'N/A'),
 ('COLLGAR', 'Scheduled (Planned)', 2017, 9, 6.36, 'N/A'),
 ('MUND', 'Opportunistic Maintenance (Planned)', 2017, 9, 0.21, 'N/A'),
 ('STHRNCRS', 'Consequential', 2016, 9, 0.22, 'N/A'),
 ('MUND', 'Opportunistic Maintenance (Planned)', 2016, 8, 0.15, 'N/A'),
 ('PMC', 'Consequential', 2017, 8, 3.52, 'N/A'),
 ('WGUTD', 'Forced', 2017, 8, 3.44, 'High Risk'),
 ('ENRG', 'Consequential', 2017, 7, 0.27, 'N/A'),
 ('ENRG', 'Forced', 2017, 7, 0.26, 'Low risk'),
 ('MELK', 'Consequential', 2016, 7, 0.76, 'N/A'),
 ('MUND', 'Scheduled (Planned)', 2017, 7, 1.7, 'N/A'),
 ('PUG', 'Opportunistic Maintenance (Planned)', 2016, 7, 0.21, 'N/A'),
 ('KORL', 'Consequential', 2017, 6, 2.24, 'N/A'),
 ('WGUTD', 'Consequential', 2016, 6, 1.99, 'N/A'),
 ('COLLGAR', 'Consequential', 2017, 5, 0.23, 'N/A'),
 ('COLLGAR', 'Opportunistic Maintenance (Planned)', 2017, 5, 0.33, 'N/A'),
 ('TRMOS', 'Scheduled (Planned)', 2016, 5, 1.42, 'N/A'),
 ('ENRG', 'Opportunistic Maintenance (Planned)', 2016, 4, 0.47, 'N/A'),
 ('GW', 'Consequential', 2017, 4, 0.24, 'N/A'),
 ('MCG', 'Scheduled (Planned)', 2017, 4, 0.06, 'N/A'),
 ('MUND', 'Forced', 2016, 4, 0.37, 'Low risk'),
 ('TRMOS', 'Scheduled (Planned)', 2017, 4, 2.31, 'N/A'),
 ('TSLA_MGT', 'Forced', 2017, 4, 0.31, 'Low risk'),
 ('AURICON', 'Opportunistic Maintenance (Planned)', 2016, 3, 0.33, 'N/A'),
 ('ENRG', 'Opportunistic Maintenance (Planned)', 2017, 3, 0.35, 'N/A'),
 ('EUCT', 'Forced', 2017, 3, 0.03, 'Low risk'),
 ('PUG', 'Opportunistic Maintenance (Planned)', 2017, 3, 0.24, 'N/A'),
 ('AUXC', 'Scheduled (Planned)', 2016, 2, 1.25, 'N/A'),
 ('MCG', 'Consequential', 2016, 2, 0.26, 'N/A'),
 ('MCG', 'Consequential', 2017, 2, 0.23, 'N/A'),
 ('STHRNCRS', 'Consequential', 2017, 2, 0.26, 'N/A'),
 ('TSLA_MGT', 'Forced', 2016, 2, 0.25, 'Low risk'),
 ('WGUTD', 'Forced', 2016, 2, 0.02, 'Low risk'),
 ('WGUTD', 'Opportunistic Maintenance (Planned)', 2017, 2, 0.05, 'N/A'),
 ('AUXC', 'Consequential', 2016, 1, 0.96, 'N/A'),
 ('AUXC', 'Consequential', 2017, 1, 0.1, 'N/A'),
 ('AUXC', 'Scheduled (Planned)', 2017, 1, 2.88, 'N/A'),
 ('DNHR', 'Forced', 2016, 1, 0.4, 'Low risk'),
 ('DNHR', 'Forced', 2017, 1, 0.48, 'Low risk'),
 ('MCG', 'Forced', 2016, 1, 0.79, 'Medium Risk'),
 ('MCG', 'Scheduled (Planned)', 2016, 1, 1.42, 'N/A'),
 ('PMC', 'Opportunistic Maintenance (Planned)', 2016, 1, 0.08, 'N/A'),
 ('PMC', 'Opportunistic Maintenance (Planned)', 2017, 1, 0.25, 'N/A'),
 ('STHRNCRS', 'Opportunistic Maintenance (Planned)', 2017, 1, 0.06, 'N/A'),
 ('TRMOS', 'Opportunistic Maintenance (Planned)', 2016, 1, 0.06, 'N/A'),
 ('WGUTD', 'Consequential', 2017, 1, 0.04, 'N/A'),
 ('WGUTD', 'Opportunistic Maintenance (Planned)', 2016, 1, 0.6, 'N/A'),
 ('WGUTD', 'Scheduled (Planned)', 2017, 1, 10.58, 'N/A')]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

 * sqlite:///AEMR.db
Done.

[('AURICON', 'Scheduled (Planned)', 2016, 46, 1.89, 'N/A'),
 ('AURICON', 'Scheduled (Planned)', 2017, 45, 1.45, 'N/A'),
 ('AURICON', 'Opportunistic Maintenance (Planned)', 2016, 3, 0.33, 'N/A')]

<h3 style="color:#D4AF37"> ‚ö° Part II. Energy Losses & Market Reliability ‚ö° </h3>

When an energy provider provides energy to the market, they are making a commitment to the market and saying; ‚ÄúWe will supply X amount of energy to the market under a contractual obligation.‚Äù However, in a situation where the outages are Forced, the energy provider intended to provide energy but are unable to provide energy and are forced offline. <b style="color:Maroon">If many energy providers are forced offline at the same time it could cause an energy security risk that AEMR needs to mitigate. </b>

To ensure this doesn‚Äôt happen, the AEMR is interested in exploring the following questions:

<li> Of the outage types in 2016 and 2017, what percent were Forced Outage(s)?
<li> What was the average duration for a forced outage during both 2016 and 2017? Have we seen an increase in the average duration of forced outages?
<li> Which energy providers tended to have the largest number of forced outages?
    
<p>

<b> We'll examine this in the questions below. </b>
    
<img src = "https://media.istockphoto.com/id/1281821795/photo/market-stock-graph-and-information-with-city-light-and-electricity-and-energy-facility-banner.jpg?s=612x612&w=0&k=20&c=RSN5LqeMW28HW10aA190_DWR5YJ5tG2wixHFPBV3uZE=">

<h3 style="color:#D4AF37"> Question Six </h3>

<b> Write a SQL Statement to calculate the proportion of Forced Outages that have occurred over the 2016 - 2017 Period.
Do we observe any particular increases regarding any Outage Types over this period? </b>

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [90]:
%%sql 
select 
count(*) as Total_Number_Outages,
sum(case when outage_reason = 'Forced' then 1 else 0 END) as Total_Number_Forced_Outages_Events,year
,round(sum(case when outage_reason = 'Forced' then 1 else 0 END)*1.0/Count(*)*100,2) as pct_forced_outages
from AEMR_Outage_Table 
where status = 'Approved'
Group by year

 * sqlite:///AEMR.db
Done.

[(1931, 1264, 2016, 65.46), (2171, 1622, 2017, 74.71)]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

 * sqlite:///AEMR.db
Done.

[(1931, 1264, 65.46), (2171, 1622, 74.71)]

Great. It's clear to see now that `Forced Outages` are problematic for us. Not only are they the only outage type that generates financial losses as the Outage is unplanned, it seems there is a number of Energy Participants who have been having a significantly high number of Outages.

Now what can we do about this? 

Let's break our analysis down into Macro and Micro Analysis.
The total gives us the Overall Duration a participant is offline / has lost energy, however, it doesn't tell us how *frequently* this occurs. In other words, if we have one or two very big outages, it might contribute to very large totals.

However, perhaps an <b> average </b> can help us identify how big these Outages might really be, spread across the year!

Let's take a look.

<h3 style="color:#D4AF37"> Question Seven </h3>

Write a SQL Statement to calculate the `Total Number of Outages`, `Total Duration In Days`and `Total Energy Lost` of all valid `Outages` for each `participant code` and `facility_code`, sorted by `Total Energy Lost` in descending order and Ordered by the YEAR Category.

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [7]:
%%sql
select 
count(*) as Total_Number_Outages,
Round(Sum(ABS((Julianday(End_Time)- Julianday(Start_Time)))),2) as Total_Duration_In_Days,
Round(Sum(Energy_Lost_MW),2) as Total_Energy_Lost,
Outage_Reason,
Participant_Code,
Facility_Code,
Year
From 
AEMR_Outage_table
Where Status = 'Approved' 
Group by Outage_Reason, Participant_Code,
Facility_Code,
Year
Order by  Total_Duration_In_Days Desc, Year Desc

 * sqlite:///AEMR.db
Done.

[(177, 404.15, 10285.4, 'Forced', 'MELK', 'MELK_G7', 2017),
 (227, 240.69, 19326.56, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (157, 129.6, 13771.07, 'Forced', 'MELK', 'MELK_G7', 2016),
 (317, 120.6, 15751.38, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (81, 98.79, 5881.52, 'Forced', 'PJRH', 'PJRH_GT11', 2016),
 (76, 91.79, 4679.68, 'Forced', 'KORL', 'KORL_GT3', 2017),
 (172, 71.9, 5016.67, 'Forced', 'TRMOS', 'TIWEST_COG1', 2017),
 (11, 64.9, 64.8, 'Forced', 'EUCT', 'GRASMERE_WF1', 2016),
 (45, 62.1, 2787.06, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (72, 60.13, 4839.28, 'Forced', 'PJRH', 'PJRH_GT11', 2017),
 (21, 47.04, 1182.8, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (69, 34.06, 9093.09, 'Forced', 'PMC', 'PMC_AG', 2016),
 (490, 33.65, 21639.55, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (135, 33.4, 4112.1, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (29, 32.33, 4320.86, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (8, 27.54, 221.29, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (24, 22.17, 815.47, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (53, 20.0, 4040.32, 'Forced', 'KORL', 'KORL_GT3', 2016),
 (206, 16.04, 2734.14, 'Forced', 'AUXC', 'AUXC_WGP', 2016),
 (208, 15.06, 10696.28, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (65, 12.63, 1232.43, 'Forced', 'TRMOS', 'TIWEST_COG1', 2016),
 (18, 4.65, 292.7, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2017),
 (13, 4.29, 299.0, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2016),
 (12, 3.4, 563.33, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2017),
 (15, 2.85, 398.58, 'Forced', 'MUND', 'MUNDARING_GT1', 2017),
 (120, 2.1, 1768.76, 'Forced', 'AUXC', 'AUXC_WGP', 2017),
 (7, 1.85, 191.86, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2017),
 (40, 1.56, 5648.44, 'Forced', 'PMC', 'PMC_AG', 2017),
 (4, 1.48, 147.2, 'Forced', 'MUND', 'MUNDARING_GT1', 2016),
 (4, 1.23, 169.9, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2017),
 (1, 0.79, 55.0, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2016),
 (2, 0.5, 160.0, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2016),
 (1, 0.48, 1.44, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2017),
 (1, 0.4, 1.44, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2016),
 (3, 0.1, 64.8, 'Forced', 'EUCT', 'GRASMERE_WF1', 2017),
 (2, 0.04, 54.0, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2016)]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

 * sqlite:///AEMR.db
Done.

[(70, 482.58, 7499.28, 'Scheduled (Planned)', 'MELK', 'MELK_G7', 2017),
 (177, 404.15, 10285.4, 'Forced', 'MELK', 'MELK_G7', 2017),
 (85, 392.25, 9668.79, 'Scheduled (Planned)', 'MELK', 'MELK_G7', 2016),
 (227, 240.69, 19326.56, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (45, 199.4, 6450.0, 'Scheduled (Planned)', 'GW', 'BW1_GREENWATERS_G2', 2016)]

<h3 style="color:#D4AF37"> Question Eight </h3>

<b> Write a SQL Statement to calculate the `Average Duration In Days`and `Average Energy Lost` of all valid `FORCED OUTAGES` for each `participant code` and `facility_code` sorted by `Average Energy Lost` in descending order and Ordered by the YEAR Category.

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [97]:
%%sql
select 
Round(AVG(ABS((Julianday(End_Time)- Julianday(Start_Time)))),2) as AVG_Duration_In_Days,
Round(AVG(Energy_Lost_MW),2) as AVG_Energy_Lost,
Outage_Reason,
Participant_Code,
Facility_Code,
Year
From 
AEMR_Outage_table
Where Status = 'Approved' and Outage_Reason = 'Forced'
Group by Outage_Reason, Participant_Code,
Facility_Code,
Year
Order by  AVG_Energy_Lost Desc, Year Desc

 * sqlite:///AEMR.db
Done.

[(1.11, 149.0, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (0.04, 141.21, 'Forced', 'PMC', 'PMC_AG', 2017),
 (0.49, 131.78, 'Forced', 'PMC', 'PMC_AG', 2016),
 (0.83, 87.71, 'Forced', 'MELK', 'MELK_G7', 2016),
 (1.06, 85.14, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (0.25, 80.0, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2016),
 (0.38, 76.23, 'Forced', 'KORL', 'KORL_GT3', 2016),
 (1.22, 72.61, 'Forced', 'PJRH', 'PJRH_GT11', 2016),
 (0.84, 67.21, 'Forced', 'PJRH', 'PJRH_GT11', 2017),
 (1.38, 61.93, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (1.21, 61.57, 'Forced', 'KORL', 'KORL_GT3', 2017),
 (2.28, 58.11, 'Forced', 'MELK', 'MELK_G7', 2017),
 (2.24, 56.32, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (0.79, 55.0, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2016),
 (0.07, 51.42, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (0.38, 49.69, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (0.28, 46.94, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2017),
 (0.07, 44.16, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (0.31, 42.48, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2017),
 (0.37, 36.8, 'Forced', 'MUND', 'MUNDARING_GT1', 2016),
 (0.92, 33.98, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (0.25, 30.46, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (0.42, 29.17, 'Forced', 'TRMOS', 'TIWEST_COG1', 2017),
 (3.44, 27.66, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (0.26, 27.41, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2017),
 (0.02, 27.0, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2016),
 (0.19, 26.57, 'Forced', 'MUND', 'MUNDARING_GT1', 2017),
 (0.33, 23.0, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2016),
 (0.03, 21.6, 'Forced', 'EUCT', 'GRASMERE_WF1', 2017),
 (0.19, 18.96, 'Forced', 'TRMOS', 'TIWEST_COG1', 2016),
 (0.26, 16.26, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2017),
 (0.02, 14.74, 'Forced', 'AUXC', 'AUXC_WGP', 2017),
 (0.08, 13.27, 'Forced', 'AUXC', 'AUXC_WGP', 2016),
 (5.9, 5.89, 'Forced', 'EUCT', 'GRASMERE_WF1', 2016),
 (0.48, 1.44, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2017),
 (0.4, 1.44, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2016)]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

 * sqlite:///AEMR.db
Done.

[(5.9, 5.89, 'Forced', 'EUCT', 'GRASMERE_WF1', 2016),
 (3.44, 27.66, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (2.28, 58.11, 'Forced', 'MELK', 'MELK_G7', 2017)]

<h3 style="color:#D4AF37"> Question Nine </h3>

<b> Write a SQL Statement to calculate the `Average Energy Lost` and `Total Energy Lost` for each `Facility Code` and `Participant Code` across both the 2016 and 2017 periods when the `Outage_Reason` is set to Forced. Upon completion of this, calculate the <u> percentage </u> of energy lost due to forced outages for each `Facility_Code`. Please ORDER the query by `Total Energy Lost` from 2016 to 2017.
    
From your analysis, which participants have contributed the most to the Energy Lost due to Forced Outages?

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [106]:
%%sql
Select 
Round(Avg(Energy_Lost_MW),2) as Avg_Energy_Lost,
Round(Sum(Energy_Lost_MW),2) as Total_Energy_Lost,
Round(Sum(Energy_Lost_MW) / (Select SUM(Energy_Lost_MW) From AEMR_Outage_table where status = 'Approved' and Outage_reason = 'Forced')*100,2)
as Pct_Energy_Lost,
Participant_Code, 
Facility_Code,
Year
From AEMR_Outage_Table 
Where Status = 'Approved' and Outage_Reason = 'Forced'
Group by Outage_Reason, Participant_Code, Facility_Code, Year 
Order by Total_Energy_Lost Desc, Year Desc 
Limit 5

 * sqlite:///AEMR.db
Done.

[(44.16, 21639.55, 14.21, 'AURICON', 'AURICON_PNJ_U1', 2017),
 (85.14, 19326.56, 12.69, 'GW', 'BW1_GREENWATERS_G2', 2017),
 (49.69, 15751.38, 10.34, 'GW', 'BW1_GREENWATERS_G2', 2016),
 (87.71, 13771.07, 9.04, 'MELK', 'MELK_G7', 2016),
 (51.42, 10696.28, 7.02, 'AURICON', 'AURICON_PNJ_U1', 2016)]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

 * sqlite:///AEMR.db
Done.

[(44.16, 21639.55, 14.21, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (85.14, 19326.56, 12.69, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (49.69, 15751.38, 10.34, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2016)]

<h3 style="color:#D4AF37"> Question Ten </h3>

<b>Having identified the top 3 participants by Total Energy Loss being `GW`, `MELK` and `Auricon`; Write a SQL Statement calculating the `Total_Energy_Lost` each of these three `Participant_Codes` and the `Facility_Code`. Additionally, identify the `Description_Of_Outage` associated with the highest `Total_Energy_Lost` for each of the `Participant_Codes` and `Facility_Code` for each of the three participants. 
    
<u>Lastly, calculate the percentage of Energy Loss, attributed to these reasons!</u> </b>

<b> ‚ö†Ô∏è Hint: As this is the final question, this is a bit of a <b> challenge question </b> which will involve some SQL functions you're not familiar with just yet. In the workplace, you're going to have to grow familiar with googling and searching for functions that you may have not learned or be familiar with. In this question, to identify the TOP `Description_Of_Outage` reason for each Participant, you're going to need to use `PARTITION BY`. You can read all about the approach you can take in this example <a href = "https://learnsql.com/cookbook/how-to-rank-rows-within-a-partition-in-sql/#:~:text=To%20partition%20rows%20and%20rank,rank%20rows%20within%20a%20partition."> here </a>. Good luck!

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [4]:
%%sql

select 
Participant_Code,
Facility_Code,
Description_Of_Outage,
Round(SUM(Energy_Lost_MW),2) as Total_Energy_Lost,
Round(SUM(Energy_Lost_MW)/(Select SUM(Energy_Lost_MW) From AEMR_Outage_table where status = 'Approved' and Outage_Reason= 'Forced') *100,2) as Pct_Forced
 




From AEMR_Outage_Table
      
      where Participant_Code in ('GW','MELK','AURICON') and Status = 'Approved' and Outage_Reason = 'Forced' 
      Group by Participant_Code, Facility_Code, Description_of_Outage
      Order by Participant_Code, Total_Energy_Lost Desc
      Limit 5

 * sqlite:///AEMR.db
Done.

[('AURICON', 'AURICON_PNJ_U1', 'Full unit trip', 6033.87, 3.96),
 ('AURICON', 'AURICON_PNJ_U1', 'Return to service from outage delayed', 1573.0, 1.03),
 ('AURICON', 'AURICON_PNJ_U1', 'unit maximum output was restricted to 100 MW as-generated due to high rotor temperature alarm for safety purposes', 1167.73, 0.77),
 ('AURICON', 'AURICON_PNJ_U1', 'WGP U2 vibration issues during start-up sequence.', 1140.0, 0.75),
 ('AURICON', 'AURICON_PNJ_U1', 'Unit slow to ramp up.', 676.94, 0.44)]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

Well done! That's a Wrap! We've now analyzed all the data we need to answer Management's Question.
You'll now move to the next part of your analysis where you'll be proceeding with creating your story in Tableau using the insights you've gathered from your SQL Analysis! 

Let's now switch to Part II of our Analysis in Tableau!!

<img src = https://www.energymagazine.com.au/wp-content/uploads/2021/05/shutterstock_1888482466-e1620278098312.jpg>

## Appendix: SQL Cheat Sheet

**SELECT**

```SQL
- SELECT * FROM table_name -- Select all columns from a table
- SELECT column_name(s) FROM table_name -- Select some columns from a table
- SELECT DISTINCT column_name(s) FROM table_name -- Select only the different values
- SELECT column_name(s) FROM table_name -- Select data filtered with the WHERE clause
  WHERE condition
- SELECT column_name(s) FROM table_name -- Order data by multiple columns. DESC for descending 
  ORDER BY column_1, column_2 DESC, column_3 ASC -- and ASC (optional) for ascending order
```

**Operators**
- `<` - Less than
- `>` - Greater than
- `<=` - Less than or equal
- `>=` - Greater than or equal
- `<>` - Not equal
- `=` - Equal
- `BETWEEN v1 AND v2` - Between a specified range
- `LIKE` - Search pattern. Use `%` as a wildcard. E.g., `%o%` matches "o", "bob", "blob", etc.

**Aggregate Functions**
- `AVG(column)` - Returns the average value of a column
- `COUNT(column)` - Returns the number of rows (without a NULL value) of a column
- `MAX(column)` - Returns the maximum value of a column
- `MIN(column)` - Returns the minimum value of a column
- `SUM(column)` - Returns the sum of a column
```SQL
SELECT AVG(column_name), MIN(column_name), MAX(column_name) FROM table_name
```
 
**Miscellaneous**
- `CASE...END` - Used in `SELECT` queries to alter a variable in place. E.g.
```SQL
SELECT column_name
    CASE
        WHEN column_name >= 0 THEN 'POSITIVE'
        ELSE 'NEGATIVE'
    END
FROM table
```
- `AS` - Used to rename a variable. E.g.
```SQL
SELECT SUM(column_name) AS total_column_name FROM table_name
```
- `GROUP BY` - Used to group rows that share the same value(s) in particular column(s). It is mostly used along with aggregation functions
- `ORDER BY` - Determines the order in which the rows are returned by an SQL query